### ISSUE TITLE
DNSwift and Universals are missing

### ISSUE THREAD

**Issue by ghost** [matthewsot/SharpSwift#3]
> Also check out [DNSwift](https://github.com/matthewsot/DNSwift) and [Universals](https://github.com/matthewsot/Universals) if you'd like to help by writing Swift code.

Projects are not available by mentioned links.

**Comment by matthewsot** [comment]
These are available on a different git server now:
https://lair.masot.net/git/DNSwift.git/
https://lair.masot.net/git/Universals.git/

You should be able to clone them as `git clone https://lair.masot.net/git/DNSwift.git` etc.

However, please be aware this is a ten year old codebase and likely will not work. If you are interested in maintaining an updated version that does work, I'm happy to link to it from here.
